@baseUrl = http://localhost:3333
@accessToken = {{authenticate_user.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Mario Santos",
  "email": "mariodev7@gmail.com",
  "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "mariodev7@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Teste title",
  "slug": "123456",
  "content": "TESTE"
}