@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Mario Santos",
  "email": "mariodev7@gmail.com",
  "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "mariodev7@gmail.com",
  "password": "123456"
}